-- Adds a database-assigned total order for cursor pagination.
-- Existing Todo columns and processed_events idempotency remain unchanged.

ALTER TABLE sync_changes
    ADD COLUMN IF NOT EXISTS change_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS idx_sync_changes_sequence
    ON sync_changes(change_sequence);

CREATE INDEX IF NOT EXISTS idx_sync_changes_scope
    ON sync_changes(tenant_id, entity_type, change_sequence);
